server:
  port: 4589
spring:
  datasource:
    username: root
    password: rootCharles550
    url: jdbc:mysql://localhost:3306/event
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
